spring.application.name=MvndiOverseer
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.jakarta.persistence.validation.mode=auto
# DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true